apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-fe
  template:
    metadata:
      labels:
        app: lms-fe
    spec:
      containers:
        - name: frontend-container
          image: lavanyayarlagadda24/webapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://http://a8a9f084a76ce4af0851dc788eba6713-855964390.us-east-1.elb.amazonaws.com/"
