name: pg-secret
on:
  workflow_call:
    secrets:
      POSTGRES_PASSWORD:
        required: true

jobs:
  create-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name lms-cluster

      - name: Create and apply PostgreSQL Secret
        run: |
          cat <<EOF > pg-secret.yml
          apiVersion: v1
          kind: Secret
          metadata:
            name: postgres-secret
          type: Opaque
          data:
            password: $(echo -n "${{ secrets.POSTGRES_PASSWORD }}" | base64)
          EOF

          kubectl apply -f pg-secret.yml
