apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-frontend
  labels:
    app: lms-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-fe
  template:
    metadata:
      labels:
        app: lms-fe
    spec:
      containers:
        - name: frontend-container
          image: lavanyayarlagadda24/frontend:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerhub-secret

