pipeline {
    agent {
    node {
         label 'slave'   // slave details to execute job
         }
     }
    environment {
        SONARQUBE_URL = 'http://54.153.71.48:9000'  // Your SonarQube URL
        SONARQUBE_TOKEN = credentials('sonar')  // Replace with your Jenkins credential ID
    }
    stages {
        stage('Checkout') {
            steps {
                echo "Checking out code..."
                // Checkout your code from SCM
                checkout scm
            }
        }
        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool name: 'sonarqube', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
                    withSonarQubeEnv('sonarqube') {  // Name of SonarQube instance in Jenkins configuration
                        sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=lmsbe \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=${SONARQUBE_URL} \
                        -Dsonar.login=${SONARQUBE_TOKEN}
                        """
                    }
                }
            }
        }
        stage('Post-Build Cleanup') {
            steps {
                echo "Cleaning workspace after build..."
                cleanWs()  // Optional: Clean workspace after the build
            }
        }
    }
}
