name: backend setup

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Build Docker Image from api/Dockerfile
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/api:latest ./api

      # ✅ Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/api:latest

      # ✅ Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # ✅ Set up kubeconfig for EKS
      - name: Set up kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name lms-cluster

      # ✅ Deploy to Kubernetes
      - name: Deploy Backend to Kubernetes
        run: |
          kubectl apply -f k8s/be-configmap.yml
          kubectl apply -f k8s/be-deployment.yml
          kubectl apply -f k8s/be-service.yml

      # ✅ View Backend Pod Logs
      - name: View Backend Logs
        run: |
          POD=$(kubectl get pods -l app=lms-be -o jsonpath="{.items[0].metadata.name}")
          echo "🚀 Backend Pod: $POD"
          kubectl logs $POD





