ame: backend setup
on: workflow_call
jobs:
  backend:
    runs-on: ubuntu
    steps: 
      - name: pull the image
        run: docker pull ${{ vars.DOCKER_USERNAME}}/api:latest
      
      - name: Backend Deployment
        run: |
          kubectl apply -f .github/workflows/k8s/be-configmap.yml
          kubectl apply -f .github/workflows/k8s/be-deployment.yml
          kubectl apply -f .github/workflows/k8s/be-service.yml
      - name: View Backend Logs
        run: |
          POD=$(kubectl get pods -l app=lms-be -o jsonpath="{.items[0].metadata.name}")
          echo "🚀 Backend Pod: $POD"
          kubectl logs $POD
