ame: backend setup
on: workflow_call
jobs:
  backend:
    runs-on: ubuntu
    steps: 
      - name: pull the image
        run: docker pull ${{ vars.DOCKER_USERNAME}}/api:latest
      
      - name: Backend Deployment
        run: |
          kubectl apply -f .github/workflows/k8s/be-configmap.yml
          kubectl apply -f .github/workflows/k8s/be-deployment.yml
          kubectl apply -f .github/workflows/k8s/be-service.yml
