 name: backend setup
on:
  push:
    paths:
      - "api/**"
      - "k8s/**"
      - ".github/workflows/**"
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ vars.DOCKER_USERNAME }}/api:latest
          echo "Building $IMAGE_NAME"
          docker build -t $IMAGE_NAME ./api
          echo "Pushing $IMAGE_NAME"
          docker push $IMAGE_NAME

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name lms-cluster

      - name: Deploy Backend to Kubernetes
        run: |
          kubectl apply -f k8s/be-configmap.yml
          kubectl apply -f k8s/be-deployment.yml
          kubectl apply -f k8s/be-service.yml





