name: frontend setup

on:
  push:
    paths:
      - "frontend/**"
      - "k8s/**"
      - ".github/workflows/**"

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ vars.DOCKER_USERNAME }}/frontend:latest
          echo "🔨 Building $IMAGE_NAME"
          docker build -t $IMAGE_NAME ./frontend
          echo "📤 Pushing $IMAGE_NAME"
          docker push $IMAGE_NAME

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name lms-cluster

      - name: Deploy Frontend to Kubernetes
        run: |
          kubectl apply -f k8s/fe-deployment.yml
          kubectl apply -f k8s/fe-service.yml

      - name: View Frontend Logs
        run: |
          echo "⏳ Waiting up to 180s for frontend pod to become ready..."
          if ! kubectl wait --for=condition=ready pod -l app=lms-fe --timeout=180s; then
            echo "⚠️ Pod did not become ready. Showing pod description and logs..."
          fi

          POD=$(kubectl get pods -l app=lms-fe -o jsonpath="{.items[0].metadata.name}")
          echo "🚀 Frontend Pod: $POD"

          echo "🔍 Describing pod..."
          kubectl describe pod $POD || true

          echo "📜 Frontend container logs:"
          kubectl logs $POD || true






