name: database setup
on: push
jobs:
  database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set up kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name lms-cluster
      - name: Apply all Kubernetes files
        working-directory: ./lms-app/k8s
        run: |
          kubectl apply -f pg-secret.yml
          kubectl apply -f pg-deployment.yml
          kubectl apply -f pg-service.yml
