name: database setup
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set up kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name lms_cluster
      - name: Deploy database
        run: |
          kubectl apply -f k8s/pg-secret.yml
          kubectl apply -f k8s/pg-deployment.yml
          kubectl apply -f k8s/pg-service.yml
