# .github/workflows/main-deploy.yml

name: Deploy LMS (All Services)

on:
  workflow_dispatch:

jobs:
  notify-start:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification - Start
  uses: slackapi/slack-github-action@v2.1.0
  with:
    webhook-type: incoming-webhook
    webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
    payload: |
        "text": "GitHub Actions workflow for LMS EKS deployment has started.",
        "channel": "all-project"
  call-database-workflow:
    uses: ./.github/workflows/database.yml

  backend:
    uses: ./.github/workflows/backend.yml

  frontend:
    uses: ./.github/workflows/frontend.yml

  notify-success:
    if: ${{ success() }}
    needs: [frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification - Success
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "LMS Deployment completed successfully!",
              "channel": "all-project"
            }

  notify-failure:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification - Failure
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "LMS Deployment failed. Please check logs.",
              "channel": "all-project"
            }



