name: Deploy LMS (All Services)
on:
  workflow_dispatch
jobs:
  notify-start:
    runs-on: ubuntu
    steps:
      - name: Slack Notification - Start
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "GitHub Actions workflow for LMS EKS deployment has started.",
              "channel": "all-project"
            }

  call-database-workflow:
    needs: notify-start
    uses: ./.github/workflows/database.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  backend:
    needs: call-database-workflow
    uses: ./.github/workflows/backend.yml
    with:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  frontend:
    needs: backend
    uses: ./.github/workflows/frontend.yml
    with:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  get-loadbalancer-urls:
    needs: frontend
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --region us-east-1 --name lms

      - name: Get pods
        run: kubectl get pods --all-namespaces

      - name: Debug frontend pod logs
        run: |
          echo "Getting pod name..."
          POD_NAME=$(kubectl get pods -l app=lms-fe -o jsonpath="{.items[0].metadata.name}")
          echo "Pod name: $POD_NAME"
          echo "frontend pod logs:"
          kubectl logs $POD_NAME

      - name: Run kubectl get svc
        run: kubectl get svc -A
      - name: Describe frontend pod
        run: |
          POD_NAME=$(kubectl get pods -l app=lms-fe -o jsonpath="{.items[0].metadata.name}")
          kubectl describe pod $POD_NAME


      - name: Wait for Frontend LoadBalancer to be ready
        run: |
          echo "Waiting for Frontend LoadBalancer to be ready..."
          for i in {1..10}; do
            FRONTEND_URL=$(kubectl get svc fe-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)
            if [ -n "$FRONTEND_URL" ]; then
              echo "Frontend LoadBalancer URL: http://$FRONTEND_URL"
              break
            fi
            echo "Waiting for LoadBalancer to be assigned... ($i)"
            sleep 15
          done

  notify-success:
    if: ${{ success() }}
    needs: get-loadbalancer-urls
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification - Success
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "LMS Deployment completed successfully!",
              "channel": "all-project"
            }

  notify-failure:
    if: ${{ failure() }}
    needs: [call-database-workflow, backend, frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification - Failure
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "LMS Deployment failed. Please check logs.",
              "channel": "all-project"
            }

