name: frontend-deploy

on:
  workflow_call:
    inputs:
      DOCKER_USERNAME:
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        run: |
          IMAGE=${{ inputs.DOCKER_USERNAME }}/webapp:latest
          docker build -t $IMAGE ./webapp
          docker push $IMAGE

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name lms

      - name: Deploy frontend
        run: |
          kubectl apply -f k8s/fe-configmap.yml
          kubectl apply -f k8s/fe-deployment.yml
          kubectl apply -f k8s/fe-service.yml
