name: frontend setup
on:
  workflow_call:  
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          IMAGE=${{ vars.DOCKER_USERNAME }}/frontend:latest
          docker build -t $IMAGE ./frontend
          docker push $IMAGE
